/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AttarSeriesRouteImport } from './routes/attar-series'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GiftsRouteImport } from './routes/gifts'
import { Route as PerfumeSeriesRouteImport } from './routes/perfume-series'
import { Route as SeriesSeriesNameRouteImport } from './routes/series.$seriesName'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AttarSeriesRoute = AttarSeriesRouteImport.update({
  id: '/attar-series',
  path: '/attar-series',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftsRoute = GiftsRouteImport.update({
  id: '/gifts',
  path: '/gifts',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfumeSeriesRoute = PerfumeSeriesRouteImport.update({
  id: '/perfume-series',
  path: '/perfume-series',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesSeriesNameRoute = SeriesSeriesNameRouteImport.update({
  id: '/series/$seriesName',
  path: '/series/$seriesName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/attar-series': typeof AttarSeriesRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/gifts': typeof GiftsRoute
  '/perfume-series': typeof PerfumeSeriesRoute
  '/series/$seriesName': typeof SeriesSeriesNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/attar-series': typeof AttarSeriesRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/gifts': typeof GiftsRoute
  '/perfume-series': typeof PerfumeSeriesRoute
  '/series/$seriesName': typeof SeriesSeriesNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/attar-series': typeof AttarSeriesRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/gifts': typeof GiftsRoute
  '/perfume-series': typeof PerfumeSeriesRoute
  '/series/$seriesName': typeof SeriesSeriesNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/attar-series'
    | '/cart'
    | '/contact'
    | '/gifts'
    | '/perfume-series'
    | '/series/$seriesName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/attar-series'
    | '/cart'
    | '/contact'
    | '/gifts'
    | '/perfume-series'
    | '/series/$seriesName'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/attar-series'
    | '/cart'
    | '/contact'
    | '/gifts'
    | '/perfume-series'
    | '/series/$seriesName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AttarSeriesRoute: typeof AttarSeriesRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  GiftsRoute: typeof GiftsRoute
  PerfumeSeriesRoute: typeof PerfumeSeriesRoute
  SeriesSeriesNameRoute: typeof SeriesSeriesNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attar-series': {
      id: '/attar-series'
      path: '/attar-series'
      fullPath: '/attar-series'
      preLoaderRoute: typeof AttarSeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gifts': {
      id: '/gifts'
      path: '/gifts'
      fullPath: '/gifts'
      preLoaderRoute: typeof GiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfume-series': {
      id: '/perfume-series'
      path: '/perfume-series'
      fullPath: '/perfume-series'
      preLoaderRoute: typeof PerfumeSeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$seriesName': {
      id: '/series/$seriesName'
      path: '/series/$seriesName'
      fullPath: '/series/$seriesName'
      preLoaderRoute: typeof SeriesSeriesNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AttarSeriesRoute: AttarSeriesRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  GiftsRoute: GiftsRoute,
  PerfumeSeriesRoute: PerfumeSeriesRoute,
  SeriesSeriesNameRoute: SeriesSeriesNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
